version: '3'

services:
  db:
    image: postgres:11
    restart: always

  server:
    build:
      context: .
      dockerfile: operations/django/Dockerfile
    volumes:
      - "shared-mount:/var/tmp/shared-mount"
    environment:
      - "DJANGO_SETTINGS_MODULE=django_conf.settings"
      - "ENVIRONMENT=development"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD="
      - "DB_HOST=db"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: operations/nginx/Dockerfile
    volumes:
      - "shared-mount:/var/tmp/shared-mount"
    ports:
      - "8000:80"
    depends_on:
      - server

volumes:
  shared-mount:
