[tool.black]
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | env
    | venv
    | build
    | dist
  )/
  | django_conf/settings.py
  | db_layer/migrations/
)
'''
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_third_party = "attrs,twilio"
