version: 2.1

jobs:
  gatekeeper_test:
    docker:
      - image: benmoose/gatekeeper-builder
    steps:
      - checkout
#      - setup_remote_docker
#      - run:
#          name: Build images
#          command: |
#            docker-compose build
      - run:
          name: Check code style
          command: |
            ./run-linter.sh --check
      - run:
          name: Run tests
          command: |
            ./run-tests.sh -vv

workflows:
  version: 2
  gatekeeper_pipeline:
    jobs:
      - gatekeeper_test
