# Generated by Django 2.2.1 on 2019-05-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db", "0001_user")]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_on", models.DateTimeField(auto_now=True, db_index=True)),
                ("phone_number", models.CharField(db_index=True, max_length=32)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"abstract": False},
        )
    ]
