# Generated by Django 2.2.1 on 2019-05-17 07:28

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db", "0002_verification_code")]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_on", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "token_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("token_payload", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="db.User"
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
