# Generated by Django 2.2.1 on 2019-05-16 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db", "0002_verification_code")]

    operations = [
        migrations.CreateModel(
            name="RevokedRefreshToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_on", models.DateTimeField(auto_now=True, db_index=True)),
                ("token_id", models.CharField(max_length=255, unique=True)),
                ("token_issued_at", models.DateTimeField()),
                ("token_expires_at", models.DateTimeField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="db.User"
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
